# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/display_VGA/display_VGA.cache/wt [current_project]
set_property parent.project_path D:/FPGA/display_VGA/display_VGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA.xci
set_property is_locked true [get_files D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top blk_mem_VGA -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all blk_mem_VGA_

write_checkpoint -force -noxdef blk_mem_VGA.dcp

catch { report_utilization -file blk_mem_VGA_utilization_synth.rpt -pb blk_mem_VGA_utilization_synth.pb }

if { [catch {
  file copy -force D:/FPGA/display_VGA/display_VGA.runs/blk_mem_VGA_synth_1/blk_mem_VGA.dcp D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/FPGA/display_VGA/display_VGA.ip_user_files/ip/blk_mem_VGA]} {
  catch { 
    file copy -force D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_stub.v D:/FPGA/display_VGA/display_VGA.ip_user_files/ip/blk_mem_VGA
  }
}

if {[file isdir D:/FPGA/display_VGA/display_VGA.ip_user_files/ip/blk_mem_VGA]} {
  catch { 
    file copy -force D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_stub.vhdl D:/FPGA/display_VGA/display_VGA.ip_user_files/ip/blk_mem_VGA
  }
}
