# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA.xci
# IP: The module: 'blk_mem_VGA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_VGA'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA.xci
# IP: The module: 'blk_mem_VGA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/blk_mem_VGA/blk_mem_VGA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
