# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/FPGA/display_VGA/display_VGA.cache/wt [current_project]
set_property parent.project_path D:/FPGA/display_VGA/display_VGA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files c:/Users/Liukun/Desktop/CrazyBird.coe
add_files -quiet d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/clk_VGA/clk_VGA.dcp
set_property used_in_implementation false [get_files d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/clk_VGA/clk_VGA.dcp]
add_files -quiet d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/shift_ram_3x3_8bits/shift_ram_3x3_8bits.dcp
set_property used_in_implementation false [get_files d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/shift_ram_3x3_8bits/shift_ram_3x3_8bits.dcp]
add_files -quiet d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/shift_ram_3x3_1bit/shift_ram_3x3_1bit.dcp
set_property used_in_implementation false [get_files d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/shift_ram_3x3_1bit/shift_ram_3x3_1bit.dcp]
add_files -quiet D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/Uart_VGA_ram/Uart_VGA_ram.dcp
set_property used_in_implementation false [get_files D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/Uart_VGA_ram/Uart_VGA_ram.dcp]
read_verilog -library xil_defaultlib {
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/delay_nclk.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/compare.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/RGB2Grey.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/headfile.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/three_fsm.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/sobel_edge_detect.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/median_filter.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/erode.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/dilate.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/Uart_receiver_1byte.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/clk_divider_precise.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/process_pic.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/scan.v
  D:/FPGA/display_VGA/display_VGA.srcs/sources_1/new/disp_VGA.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/display_VGA/display_VGA.srcs/constrs_1/new/top_xdc.xdc
set_property used_in_implementation false [get_files D:/FPGA/display_VGA/display_VGA.srcs/constrs_1/new/top_xdc.xdc]


synth_design -top disp_VGA -part xc7a100tcsg324-1


write_checkpoint -force -noxdef disp_VGA.dcp

catch { report_utilization -file disp_VGA_utilization_synth.rpt -pb disp_VGA_utilization_synth.pb }
