set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp/clk_VGA_in_context.xdc rfile:../dcp/clk_VGA_in_context.xdc id:1 order:EARLY scoped_inst:U_Clk} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_2/shift_ram_3x3_8bits_in_context.xdc rfile:../dcp_2/shift_ram_3x3_8bits_in_context.xdc id:2 order:EARLY scoped_inst:U_process_pic/U_med/U_shift_ram1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_2/shift_ram_3x3_8bits_in_context.xdc rfile:../dcp_2/shift_ram_3x3_8bits_in_context.xdc id:3 order:EARLY scoped_inst:U_process_pic/U_med/U_shift_ram0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_2/shift_ram_3x3_8bits_in_context.xdc rfile:../dcp_2/shift_ram_3x3_8bits_in_context.xdc id:4 order:EARLY scoped_inst:U_process_pic/U_sobel_detect/U_shift_ram1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_2/shift_ram_3x3_8bits_in_context.xdc rfile:../dcp_2/shift_ram_3x3_8bits_in_context.xdc id:5 order:EARLY scoped_inst:U_process_pic/U_sobel_detect/U_shift_ram0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_3/shift_ram_3x3_1bit_in_context.xdc rfile:../dcp_3/shift_ram_3x3_1bit_in_context.xdc id:6 order:EARLY scoped_inst:U_process_pic/U_erode/U_shift_ram_3x3_1bit1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_3/shift_ram_3x3_1bit_in_context.xdc rfile:../dcp_3/shift_ram_3x3_1bit_in_context.xdc id:7 order:EARLY scoped_inst:U_process_pic/U_erode/U_shift_ram_3x3_1bit0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_3/shift_ram_3x3_1bit_in_context.xdc rfile:../dcp_3/shift_ram_3x3_1bit_in_context.xdc id:8 order:EARLY scoped_inst:U_process_pic/U_dilate/U_shift_ram_3x3_1bit1} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_3/shift_ram_3x3_1bit_in_context.xdc rfile:../dcp_3/shift_ram_3x3_1bit_in_context.xdc id:9 order:EARLY scoped_inst:U_process_pic/U_dilate/U_shift_ram_3x3_1bit0} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.runs/synth_1/.Xil/Vivado-17012-Liukun/dcp_4/Uart_VGA_ram_in_context.xdc rfile:../dcp_4/Uart_VGA_ram_in_context.xdc id:10 order:EARLY scoped_inst:U_Uart_VGA_ram} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA/display_VGA/display_VGA.srcs/constrs_1/new/top_xdc.xdc rfile:../../../../../display_VGA.srcs/constrs_1/new/top_xdc.xdc id:11} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_Clk]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_med/U_shift_ram1/CLK]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_med/U_shift_ram1]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_med/U_shift_ram0/CLK]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_med/U_shift_ram0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_sobel_detect/U_shift_ram1/CLK]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_sobel_detect/U_shift_ram1]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_sobel_detect/U_shift_ram0/CLK]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_sobel_detect/U_shift_ram0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_erode/U_shift_ram_3x3_1bit1/CLK]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_erode/U_shift_ram_3x3_1bit1]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_erode/U_shift_ram_3x3_1bit0/CLK]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_erode/U_shift_ram_3x3_1bit0]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_dilate/U_shift_ram_3x3_1bit1/CLK]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_dilate/U_shift_ram_3x3_1bit1]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins U_process_pic/U_dilate/U_shift_ram_3x3_1bit0/CLK]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_process_pic/U_dilate/U_shift_ram_3x3_1bit0]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins U_Uart_VGA_ram/clka]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins U_Uart_VGA_ram/clkb]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells U_Uart_VGA_ram]
set_property src_info {type:XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[11]}]
set_property src_info {type:XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[10]}]
set_property src_info {type:XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[9]}]
set_property src_info {type:XDC file:11 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[8]}]
set_property src_info {type:XDC file:11 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[7]}]
set_property src_info {type:XDC file:11 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[6]}]
set_property src_info {type:XDC file:11 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[5]}]
set_property src_info {type:XDC file:11 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[4]}]
set_property src_info {type:XDC file:11 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[3]}]
set_property src_info {type:XDC file:11 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[2]}]
set_property src_info {type:XDC file:11 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[1]}]
set_property src_info {type:XDC file:11 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_data[0]}]
set_property src_info {type:XDC file:11 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:11 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property src_info {type:XDC file:11 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]
set_property src_info {type:XDC file:11 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property src_info {type:XDC file:11 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[3]}]
set_property src_info {type:XDC file:11 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[2]}]
set_property src_info {type:XDC file:11 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[1]}]
set_property src_info {type:XDC file:11 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {choose[0]}]
set_property src_info {type:XDC file:11 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]
set_property src_info {type:XDC file:11 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]
set_property src_info {type:XDC file:11 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property src_info {type:XDC file:11 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property src_info {type:XDC file:11 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property src_info {type:XDC file:11 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property src_info {type:XDC file:11 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property src_info {type:XDC file:11 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property src_info {type:XDC file:11 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property src_info {type:XDC file:11 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property src_info {type:XDC file:11 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property src_info {type:XDC file:11 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property src_info {type:XDC file:11 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property src_info {type:XDC file:11 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property src_info {type:XDC file:11 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property src_info {type:XDC file:11 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property src_info {type:XDC file:11 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins U_Clk/clk_100m]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 7.500 15.000} [get_pins U_Clk/clk_40m]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk] -edges {1 2 3} -edge_shift {0.000 1.250 2.500} [get_pins U_Clk/clk_80m]
