# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/Uart_VGA_ram/Uart_VGA_ram.xci
# IP: The module: 'Uart_VGA_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/Uart_VGA_ram/Uart_VGA_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uart_VGA_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/Uart_VGA_ram/Uart_VGA_ram.xci
# IP: The module: 'Uart_VGA_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/display_VGA/display_VGA.srcs/sources_1/ip/Uart_VGA_ram/Uart_VGA_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uart_VGA_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
