######################################################################
#
# File name : delay_nclk_yb_compile.do
# Created on: Sun Dec 16 21:38:17 +0800 2018
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../display_VGA.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"delay_nclk_yb_func_synth.v" \
"../../../../display_VGA.srcs/sources_1/new/compare.v" \
"../../../../display_VGA.srcs/sources_1/new/median_filter.v" \
"../../../../display_VGA.srcs/sim_1/new/delay_nclk_yb.v" \


quit -force

