######################################################################
#
# File name : delay_nclk_yb.udo
# Created on: Sun Dec 16 21:57:08 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
