######################################################################
#
# File name : disp_VGA.udo
# Created on: Fri Dec 07 16:31:39 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
