######################################################################
#
# File name : three_fsm_tb_wave.do
# Created on: Thu Jan 03 13:32:03 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
