######################################################################
#
# File name : three_fsm_tb_simulate.do
# Created on: Thu Jan 03 13:32:03 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L xpm -lib xil_defaultlib xil_defaultlib.three_fsm_tb xil_defaultlib.glbl

do {three_fsm_tb_wave.do}

view wave
view structure
view signals

do {three_fsm_tb.udo}

run 50000000ns
