######################################################################
#
# File name : three_fsm_tb_compile.do
# Created on: Thu Jan 03 13:31:53 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xpm

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vmap xpm msim/xpm

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../display_VGA.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

C:\\modeltech_pe_10.4c\\win32pe\\vcom -64 -93 -work xpm  \
"C:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../display_VGA.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../display_VGA.srcs/sources_1/new/three_fsm.v" \
"../../../display_VGA.srcs/sim_1/new/three_fsm_tb.v" \

# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

