######################################################################
#
# File name : Uart_receiver_tb.udo
# Created on: Sun Dec 23 21:27:43 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
